# Generated by Django 5.0.6 on 2024-06-24 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0002_alter_todo_options_todo_description_todo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='description',
        ),
    ]
